//
// Created by Fushenshen on 2022/7/23.
//

#ifndef TRAFFICPROCESS_INCLUDE_TRAFFIC_FRAME_HPP_
#define TRAFFICPROCESS_INCLUDE_TRAFFIC_FRAME_HPP_
class Frame{


};
#endif //TRAFFICPROCESS_INCLUDE_TRAFFIC_FRAME_HPP_
