//
// Created by Fushenshen on 2022/7/23.
//

#ifndef TRAFFICPROCESS_INCLUDE_TRAFFIC_TYPE_HPP_
#define TRAFFICPROCESS_INCLUDE_TRAFFIC_TYPE_HPP_
enum class TrafficType {
  TRAFFIC_UNKNOWN = -1,
  TRAFFIC_BASE_DETECTION = 0,
  TRAFFIC_CONVERSE_DRIVING = 1,
  TRAFFIC_ILLEGAL_STOPPING = 2,
};
#endif //TRAFFICPROCESS_INCLUDE_TRAFFIC_TYPE_HPP_
